server:
  port: 8084
  context-path: /
logging:
  level: trace
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /console